pipeline:
  build:
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+drone
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/sonar-scanner-node
    secrets: [ docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: [push, tag]

  build_tag:
    environment:
      - DOCKER_USERNAME= quay.io/ukhomeofficedigital+drone
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/sonar-scanner-node
    secrets: [ docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
